Importing the Modules needed for the models

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

Loading the Data

In [2]:
lung_data=pd.read_csv("Lung_Data.csv")

In [3]:
lung_data

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1   
1        M   74        2               1        1              1   
2        F   59        1               1        1              2   
3        M   63        2               2        2              1   
4        F   63        1               2        1              1   
..     ...  ...      ...             ...      ...            ...   
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                  1        2        1         2                  2         2   
1                  2        2        2         1                  1         1   
2                  1        2        1         2                  1         2   
3                  1        1        1         1                  2         1   
4                  1        1        1         2                  1         2   
..               ...      ...      ...       ...                ...       ...   
304                2        2        1         1                  2         2   
305                1        2        2         2                  2         2   
306                1        1        2         2                  2         2   
307                1        2        2         1                  2         2   
308                1        2        2         2                  2         1   

     SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                      2                      2           2         YES  
1                      2                      2           2         YES  
2                      2                      1           2          NO  
3                      1                      2           2          NO  
4                      2                      1           1          NO  
..                   ...                    ...         ...         ...  
304                    2                      2           1         YES  
305                    2                      1           2         YES  
306                    1                      1           2         YES  
307                    2                      1           2         YES  
308                    1                      2           1         YES  

[309 rows x 16 columns]

In [4]:
lung_data.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1        2        1         2                  2         2   
1                2        2        2         1                  1         1   
2                1        2        1         2                  1         2   
3                1        1        1         1                  2         1   
4                1        1        1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [5]:
lung_data.tail()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL CONSUMING  COUGHING  \
304                2        2        1         1                  2         2   
305                1        2        2         2                  2         2   
306                1        1        2         2                  2         2   
307                1        2        2         1                  2         2   
308                1        2        2         2                  2         1   

     SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
304                    2                      2           1         YES  
305                    2                      1           2         YES  
306                    1                      1           2         YES  
307                    2                      1           2         YES  
308                    1                      2           1         YES

DATA ENCODING:

In [6]:
    lung_data.GENDER = lung_data.GENDER.map({"M":1,"F":2})
    lung_data.LUNG_CANCER = lung_data.LUNG_CANCER.map({"YES":1,"NO":2})

Defining the Dependent and Independent Variables in the form of X and Y respectively

In [7]:
x=lung_data[['GENDER','AGE','SMOKING','YELLOW_FINGERS','ANXIETY','PEER_PRESSURE','CHRONIC DISEASE','FATIGUE','ALLERGY','WHEEZING','ALCOHOL CONSUMING','COUGHING','SHORTNESS OF BREATH','SWALLOWING DIFFICULTY','CHEST PAIN'
]] #dependent_variables
y=lung_data['LUNG_CANCER'] #independent_variable

In [8]:
x=lung_data.iloc[:,0:-2]
x

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        1               2        2              1   
1         1   74        2               1        1              1   
2         2   59        1               1        1              2   
3         1   63        2               2        2              1   
4         2   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304       2   56        1               1        1              2   
305       1   70        2               1        1              1   
306       1   58        2               1        1              1   
307       1   67        2               1        2              1   
308       1   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                  1        2        1         2                  2         2   
1                  2        2        2         1                  1         1   
2                  1        2        1         2                  1         2   
3                  1        1        1         1                  2         1   
4                  1        1        1         2                  1         2   
..               ...      ...      ...       ...                ...       ...   
304                2        2        1         1                  2         2   
305                1        2        2         2                  2         2   
306                1        1        2         2                  2         2   
307                1        2        2         1                  2         2   
308                1        2        2         2                  2         1   

     SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  
0                      2                      2  
1                      2                      2  
2                      2                      1  
3                      1                      2  
4                      2                      1  
..                   ...                    ...  
304                    2                      2  
305                    2                      1  
306                    1                      1  
307                    2                      1  
308                    1                      2  

[309 rows x 14 columns]

In [9]:
y=lung_data.iloc[:,-1:]
y

LUNG_CANCER
0              1
1              1
2              2
3              2
4              2
..           ...
304            1
305            1
306            1
307            1
308            1

[309 rows x 1 columns]

Dimensionality Check

In [10]:
lung_data.shape

(309, 16)

Checking Null Values

In [11]:
lung_data.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

Checking the Data Types

In [12]:
lung_data.dtypes

GENDER                   int64
AGE                      int64
SMOKING                  int64
YELLOW_FINGERS           int64
ANXIETY                  int64
PEER_PRESSURE            int64
CHRONIC DISEASE          int64
FATIGUE                  int64
ALLERGY                  int64
WHEEZING                 int64
ALCOHOL CONSUMING        int64
COUGHING                 int64
SHORTNESS OF BREATH      int64
SWALLOWING DIFFICULTY    int64
CHEST PAIN               int64
LUNG_CANCER              int64
dtype: object

About the Data

In [13]:
lung_data.describe()

GENDER         AGE     SMOKING  YELLOW_FINGERS     ANXIETY  \
count  309.000000  309.000000  309.000000      309.000000  309.000000   
mean     1.475728   62.673139    1.563107        1.569579    1.498382   
std      0.500221    8.210301    0.496806        0.495938    0.500808   
min      1.000000   21.000000    1.000000        1.000000    1.000000   
25%      1.000000   57.000000    1.000000        1.000000    1.000000   
50%      1.000000   62.000000    2.000000        2.000000    1.000000   
75%      2.000000   69.000000    2.000000        2.000000    2.000000   
max      2.000000   87.000000    2.000000        2.000000    2.000000   

       PEER_PRESSURE  CHRONIC DISEASE     FATIGUE     ALLERGY    WHEEZING  \
count     309.000000       309.000000  309.000000  309.000000  309.000000   
mean        1.501618         1.504854    1.673139    1.556634    1.556634   
std         0.500808         0.500787    0.469827    0.497588    0.497588   
min         1.000000         1.000000    1.000000    1.000000    1.000000   
25%         1.000000         1.000000    1.000000    1.000000    1.000000   
50%         2.000000         2.000000    2.000000    2.000000    2.000000   
75%         2.000000         2.000000    2.000000    2.000000    2.000000   
max         2.000000         2.000000    2.000000    2.000000    2.000000   

       ALCOHOL CONSUMING    COUGHING  SHORTNESS OF BREATH  \
count         309.000000  309.000000           309.000000   
mean            1.556634    1.579288             1.640777   
std             0.497588    0.494474             0.480551   
min             1.000000    1.000000             1.000000   
25%             1.000000    1.000000             1.000000   
50%             2.000000    2.000000             2.000000   
75%             2.000000    2.000000             2.000000   
max             2.000000    2.000000             2.000000   

       SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
count             309.000000  309.000000   309.000000  
mean                1.469256    1.556634     1.126214  
std                 0.499863    0.497588     0.332629  
min                 1.000000    1.000000     1.000000  
25%                 1.000000    1.000000     1.000000  
50%                 1.000000    2.000000     1.000000  
75%                 2.000000    2.000000     1.000000  
max                 2.000000    2.000000     2.000000

In [14]:
lung_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    int64
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    i

Splitting the dataset : Training and Testing the dataset

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/3,random_state=0)

In [16]:
len(lung_data)

309

In [17]:
len(x_test)

103

In [18]:
len(x_train)

206

In [19]:
print('X train shape: ', x_train.shape)
print('Y train shape: ', y_train.shape)
print('X test shape: ', x_test.shape)
print('Y test shape: ', y_test.shape)

X train shape:  (206, 14)
Y train shape:  (206, 1)
X test shape:  (103, 14)
Y test shape:  (103, 1)


======================================================================================================================

LOGISTIC REGRESSION

In [20]:
#Logistic Regression
Model1 = LogisticRegression()
Model1.fit(x_train, y_train)
prediction1 = Model1.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
#prediction1 = Model1.predict(y_test)

In [22]:
prediction1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

CONFUSION MATRIX FOR PREDICTION 1:

In [23]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_test,prediction1)

array([[86,  1],
       [ 8,  8]], dtype=int64)

ACCURACY FOR PREDICTION 1:

In [24]:
accuracy_score(y_test,prediction1)

0.912621359223301

PRECISION FOR PREDICTION 1 :

In [27]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction1, average = None)

array([0.91489362, 0.88888889])

RECALL FOR PREDICTION 1 :

In [28]:
recall_score(y_test, prediction1, average = None)

array([0.98850575, 0.5       ])

F1_SCORE

In [29]:
f1_score(y_test, prediction1, average = None)

array([0.95027624, 0.64      ])

======================================================================================================================

KNN :

In [30]:
#KNeighborsClassifier
import warnings
warnings.filterwarnings("ignore")
from sklearn.neighbors import KNeighborsClassifier
#Fitting K-NN to the Training set
classifier = KNeighborsClassifier(n_neighbors = 3, metric = "minkowski", p = 2)
classifier.fit(x_train, y_train)
#Predicting the Test set result
prediction2 = classifier.predict(x_test)

In [31]:
#prediction2 = classifier.predict(y_test)

In [32]:
prediction2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

CONFUSION MATRIX FOR PRDICTION 2 :

In [33]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_test,prediction2)

array([[84,  3],
       [12,  4]], dtype=int64)

ACCURACY FOR PREDICTION 2 :

In [34]:
accuracy_score(y_test,prediction2)

0.8543689320388349

PRECISION FOR PREDICTION 2 :

In [35]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction2, average = None)

array([0.875     , 0.57142857])

RECALL FOR PREDICTION 2 :

In [36]:
recall_score(y_test, prediction2, average = None)

array([0.96551724, 0.25      ])

F1_SCORE

In [37]:
f1_score(y_test, prediction2, average = None)

array([0.91803279, 0.34782609])

=======================================================================================================================

DECISION TREE :

In [38]:
#Decision Tree       
from sklearn.tree import DecisionTreeClassifier  
tree = DecisionTreeClassifier(random_state = 0,criterion = "entropy")        
tree.fit(x_train, y_train)
prediction3 = classifier.predict(x_test)

In [39]:
prediction3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

CONFUSION MATRIX FOR PREDICTION 3:

In [40]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_test,prediction3)

array([[84,  3],
       [12,  4]], dtype=int64)

ACCURACY FOR PREDICTION 3 :

In [41]:
accuracy_score(y_test,prediction3)

0.8543689320388349

PRECISION FOR PREDICTION 3 :

In [42]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction3, average = None)

array([0.875     , 0.57142857])

RECALL FOR PREDICTION 3 :

In [43]:
recall_score(y_test, prediction3, average = None)

array([0.96551724, 0.25      ])

F1_SCORE

In [44]:
f1_score(y_test, prediction3, average = None)

array([0.91803279, 0.34782609])

========================================================================================================================

EVALUATION METRICS

In [45]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import recall_score
confusion_matrix(y_test, prediction1)

array([[86,  1],
       [ 8,  8]], dtype=int64)

In [46]:
accuracy_score(y_test, prediction1)

0.912621359223301

In [47]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction1, average = None)

array([0.91489362, 0.88888889])

In [48]:
recall_score(y_test, prediction1, average = None)

array([0.98850575, 0.5       ])

In [49]:
f1_score(y_test, prediction1, average = None)
#roc_auc_score(y_test, probs, multi_class="ovr")

array([0.95027624, 0.64      ])

======================================================================================================================

SVM

In [50]:
#Support Vector Machine
from sklearn.ensemble import BaggingClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

svm = OneVsRestClassifier(BaggingClassifier(SVC(C=10,kernel='rbf',random_state=9, probability=True),n_jobs=-1))

svm.fit(x_train, y_train)

prediction4 = svm.predict(x_test)

CONFUSION MATRIX FOR PREDICTION 4 :

In [51]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_test,prediction4)

array([[87,  0],
       [16,  0]], dtype=int64)

ACCURACY FOR PREDICTION 4 :

In [52]:
accuracy_score(y_test,prediction4)

0.8446601941747572

PRECISION FOR PREDICTION 4 :

In [53]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction4, average = None)

array([0.84466019, 0.        ])

RECALL FOR PREDICTION 4 :

In [54]:
recall_score(y_test, prediction4, average = None)

array([1., 0.])

F1_SCORE

In [55]:
f1_score(y_test, prediction4, average = None)

array([0.91578947, 0.        ])

====================================================================================================================

NAIVE BAYES ALGORITHM :

In [56]:
from sklearn.naive_bayes import GaussianNB

nbcla = GaussianNB()

nbcla.fit(x_train, y_train)

prediction5 = nbcla.predict(x_test)

CONFUSION MATRIX FOR PREDICTION 5 :

In [57]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_test,prediction5)

array([[83,  4],
       [10,  6]], dtype=int64)

ACCURACY MATRIX FOR PREDICTION 5 :

In [58]:
accuracy_score(y_test,prediction5)

0.8640776699029126

PRECISION FOR PREDICTION 5 :

In [59]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction5, average = None)

array([0.89247312, 0.6       ])

RECALL FOR PREDICTION 5 :

In [60]:
recall_score(y_test, prediction5, average = None)

array([0.95402299, 0.375     ])

F1_SCORE

In [61]:
f1_score(y_test, prediction5, average = None)

array([0.92222222, 0.46153846])

ENSEMBLE ALGORITHM

In [65]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, max_features="auto",random_state=0)
clf.fit(x_train, y_train)
prediction6 = clf.predict(x_test)

ACCURACY FOR PREDICTION 6:

In [66]:
accuracy_score(y_test, y_pred)

0.9029126213592233

CONFUSION MATRIX FOR PREDICTION 6

In [67]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_test,prediction6)

array([[85,  2],
       [ 8,  8]], dtype=int64)

PRECISION FOR PREDICTION 6 :

In [68]:
probs = Model1.predict_proba(x_test)
precision_score(y_test, prediction6, average = None)

array([0.91397849, 0.8       ])

RECALL FOR PREDICTION 6 :

In [69]:
recall_score(y_test, prediction6, average = None)

array([0.97701149, 0.5       ])

F1_SCORE

In [70]:
f1_score(y_test, prediction6, average = None)

array([0.94444444, 0.61538462])